name: CI

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  #agregar Gitleaks: este sirve para escanear vulnerabilidades en el código fuente por ejemplo tokens o credenciales expuestas en el codigo fuente. 
  #Se puede agregar como un paso en el flujo de trabajo de CI para escanear el código antes de que se realice un despliegue o una fusión de cambio
  
  security-and-quality:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deteccion de secrets expuestos (gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configuracion Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./app/package-lock.json"

      - name: Instalar dependencies
        run: |
          cd app
          npm ci

      - name: Auditoria de Seguridad en Dependencias
        run: |
          cd app
          npm audit --audit-level=high --if-present

      #Escaneo de imagenes de Docker con Trivy: este paso se encarga de escanear la imagen de Docker construida para detectar vulnerabilidades de seguridad 
      #en las imagenes y contenedores de Docker  
  build-and-scan:
    needs: security-and-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build de Docker con Cache
        uses: docker/build-push-action@v6
        with:
          context: ./app
          load: true
          tags: devops-app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Escaneo de vulnerabilidades en la Imagen (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devops-app:test'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Validar sintaxis de Docker Compose
        run: docker compose config