name: CD

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CD
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-monitoring-platform
            git pull origin main
            docker compose up -d --build
            docker compose ps

      - name: Notificacion por Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELE_USER }}
          token: ${{ secrets.TELE_KEY }}
          message: |
            🚀 *Resultado del Despliegue en EC2*
            
            *Repositorio:* ${{ github.repository }}
            *Rama:* ${{ github.ref_name }}
            *Estado:* ${{ job.status == 'success' && '✅ Éxito' || '❌ Falló' }}
            *Commit:* ${{ github.sha }}